### ISSUE TITLE
Cannot register GCM on android 5+

### ISSUE THREAD

**Issue by pianetarosso** [Donky-Network/DonkySDK-Android-Modular#2]
Hi,

I've followed the guides on [here](http://docs.mobiledonky.com/docs/gcm-configuration), but when I register the app on Donky network, I get this message:

`DonkyGCMRegistrationService: Error obtaining push GCM registration token`

I debugged the exception:

`java.io.IOException: MAIN_THREAD
                                                                           at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
                                                                           at net.donky.core.gcm.DonkyGcmController.getRegistrationToken(DonkyGcmController.java:300)
                                                                           at net.donky.core.gcm.DonkyGcmController.doRegisterGCM(DonkyGcmController.java:335)
                                                                           at net.donky.core.gcm.DonkyGcmController.registerPush(DonkyGcmController.java:90)
                                                                           at net.donky.core.account.DonkyAccountController.registerPushIfEmpty(DonkyAccountController.java:1903)
                                                                           at net.donky.core.account.DonkyAccountController.handleReplaceRegistrationSuccess(DonkyAccountController.java:1760)
                                                                           at net.donky.core.account.DonkyAccountController.access$1400(DonkyAccountController.java:58)
                                                                           at net.donky.core.account.DonkyAccountController$13.success(DonkyAccountController.java:1695)
                                                                           at net.donky.core.account.DonkyAccountController$13.success(DonkyAccountController.java:1691)
                                                                           at net.donky.core.network.DonkyNetworkController$4$1.run(DonkyNetworkController.java:549)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:158)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

in this code:

` token = instanceID.getToken(senderId, GoogleCloudMessaging.INSTANCE_ID_SCOPE, null);`

in `DonkyGcmController.java`.

As stated in docs [here](https://developers.google.com/android/reference/com/google/android/gms/iid/InstanceID) you can't call that method in the main thread.

I'm doing something wrong or it's a bug?

**Comment by pianetarosso** [comment]
Created pull request with solution here: https://github.com/Donky-Network/DonkySDK-Android-Modular/pull/3
