### ISSUE TITLE
crash/error with old retrofit class

### ISSUE THREAD

**Issue by stefanomemrise** [Donky-Network/DonkySDK-Android-Modular#6]
Fatal Exception: java.lang.NoSuchMethodError: No static method a(Ljava/lang/Throwable;Ljava/io/PrintWriter;)V in class Lcom/google/devtools/build/android/desugar/runtime/ThrowableExtension; or its super classes (declaration of 'com.google.devtools.build.android.desugar.runtime.ThrowableExtension' appears in /data/app/com.google.android.apps.mtaas.crawler-1/base.apk)
at retrofit.RestAdapter.a(SourceFile:512)
at retrofit.RestAdapter$RestHandler.a(SourceFile:398)
at retrofit.RestAdapter$RestHandler.invoke(SourceFile:240)
at java.lang.reflect.Proxy.invoke(Proxy.java:393)
at $Proxy4.a(Unknown Source)
at net.donky.core.network.restapi.authentication.Register.h(SourceFile:94)
at net.donky.core.network.restapi.authentication.Register.g(SourceFile:28)
at net.donky.core.network.restapi.authentication.GenericAuthenticationServiceRequest.b(SourceFile:79)
at net.donky.core.network.DonkyNetworkController.a(SourceFile:523)
at net.donky.core.account.DonkyAccountController.a(SourceFile:1373)
at net.donky.core.account.DonkyAccountController.a(SourceFile:1326)
at net.donky.core.DonkyCore$1.run(SourceFile:350)

Would it be possible for you to update to the last Retrofit library?
You're currently using 1.9.0, Retrofit 2 (we are using 2.3.0) solves a lot of issues.

**Comment by MarcinSwierczek** [comment]
Hi @stefanomemrise,

The SDK version that supports Retrofit2 will be available shortly.

Thank you,
Marcin

**Comment by MarcinSwierczek** [comment]
The Modular SDK version 2.7.0.4 has the Retrofit library updated to v2.
